In [293]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

import os
os.chdir("/Users/AlanHDLR/Desktop")

In [295]:
data_vw = pd.read_csv("kc_house_data.csv")
data_vw

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287


In [297]:
X = data_vw[[
    'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 
    'floors', 'waterfront', 'view', 'condition', 'grade', 'yr_built', 'lat', 'long']].values
Y = data_vw[["price"]].values 

In [299]:
# Matriz X transpuesta
XT_X = np.matmul(np.matrix.transpose(X), X)
XT_X

array([[ 2.64274000e+05,  1.62054750e+05,  1.62175001e+08,
         1.12699827e+09,  1.10770500e+05,  5.38000000e+02,
         1.82950000e+04,  2.48763000e+05,  5.66268000e+05,
         1.43686638e+08,  3.46491519e+06, -8.90340471e+06],
       [ 1.62054750e+05,  1.09476812e+05,  1.06601162e+08,
         7.50973606e+08,  7.27991250e+04,  4.36500000e+02,
         1.31037500e+04,  1.54478500e+05,  3.62977500e+05,
         9.03346532e+07,  2.17384832e+06, -5.58541608e+06],
       [ 1.62175001e+08,  1.06601162e+08,  1.11727919e+11,
         8.21193670e+11,  7.09672610e+07,  5.17311000e+05,
         1.48618050e+07,  1.52504755e+08,  3.61993934e+08,
         8.87877796e+10,  2.13810548e+09, -5.49319426e+09],
       [ 1.12699827e+09,  7.50973606e+08,  8.21193670e+11,
         4.20113464e+13,  4.85388085e+08,  4.13560800e+06,
         1.27752236e+08,  1.10798376e+09,  2.61957937e+09,
         6.44942478e+11,  1.55180568e+10, -3.98747443e+10],
       [ 1.10770500e+05,  7.27991250e+04,  7.0967261

In [301]:
# Inversa de la traspuesta
XT_X_inv = np.linalg.inv(XT_X)
XT_X_inv

array([[ 8.78180491e-05, -2.93874830e-05, -5.25777879e-08,
         1.21578850e-10,  6.28594808e-06,  3.77161833e-05,
         8.09064423e-06, -5.30269643e-06,  1.35029992e-05,
         1.36208059e-07,  1.83047682e-05,  1.11466817e-05],
       [-2.93874830e-05,  2.46973082e-04, -1.01081488e-07,
         1.13791679e-10, -6.06409349e-05,  2.28399919e-06,
        -7.83201777e-06, -9.97525447e-06, -9.50410529e-06,
        -1.44449854e-06, -2.09781453e-06, -2.39856952e-05],
       [-5.25777879e-08, -1.01081488e-07,  2.28411336e-10,
        -4.05349236e-13,  1.78128297e-08, -3.55957689e-08,
        -1.77747170e-08, -1.35427707e-09, -8.26726033e-08,
         5.93446611e-10, -2.18375234e-08, -3.32543140e-09],
       [ 1.21578850e-10,  1.13791679e-10, -4.05349236e-13,
         2.83134199e-14,  1.70517015e-10,  1.52518131e-10,
        -4.36396400e-11, -6.11688753e-12,  4.57351075e-11,
        -3.08971074e-12,  1.16800833e-10,  2.25146457e-12],
       [ 6.28594808e-06, -6.06409349e-05,  1.7812829

In [303]:
XT_Y = np.matmul(np.matrix.transpose(X), Y)
XT_Y

array([[ 4.16230285e+10],
       [ 2.78943857e+10],
       [ 2.93944075e+13],
       [ 2.05809089e+14],
       [ 1.85431805e+10],
       [ 2.70885792e+08],
       [ 5.15064376e+09],
       [ 3.99857591e+10],
       [ 9.56029351e+10],
       [ 2.30199830e+13],
       [ 5.55502450e+11],
       [-1.42656948e+12]])

In [305]:
betas = np.matmul(XT_X_inv, XT_Y)
betas

array([[-3.52844463e+04],
       [ 4.60576414e+04],
       [ 1.68048254e+02],
       [-2.00730481e-01],
       [ 1.94166297e+04],
       [ 5.93533353e+05],
       [ 5.22553306e+04],
       [ 2.28360530e+04],
       [ 1.11138080e+05],
       [-3.28092639e+03],
       [ 4.86830275e+05],
       [ 1.42752607e+05]])

In [307]:
# Calculo de los prnosticos para Y de acuerdo a los coeficientes de regresión
Y_pred = np.matmul(X, betas)
Y_pred

array([[266432.49336261],
       [683098.72022675],
       [306776.7640412 ],
       ...,
       [140933.22388629],
       [414723.95732908],
       [144123.10134395]])

In [309]:
# Calculo de residuales
Resid = Y - Y_pred
Resid.round(2)

array([[ -44532.49],
       [-145098.72],
       [-126776.76],
       ...,
       [ 261167.78],
       [ -14723.96],
       [ 180876.9 ]])

In [311]:
# Calculo de la suma de residuales al cuadrado
RSS = float(np.matmul(np.matrix.transpose(Resid), Resid))
RSS

912607887984213.8

In [313]:
# Calculo de la suma total de cuadrados
TSS = float(np.matmul(np.matrix.transpose(Y), Y) - len(Y)*(Y.mean()**2))
TSS

2912916761921300.0

In [315]:
# Calculo de coeficiente de determinación 
R_cuad = float(1- RSS/TSS)
R_cuad

0.6867030668661207

In [317]:
# Calculo de coeficiente de determianción ajustado
RSqAj = float(1-(RSS/ (X.shape[0]- X.shape[1])) / (TSS / (X.shape[0]-1)))
RSqAj

0.6865435248882275

In [319]:
# Calculo de la varianza del error de regresión
s_cuad = RSS / (len(Y) - X.shape[1])
s_cuad

42248409239.58214

In [321]:
# Desviación estandar del error de regresión
import math
s = math.sqrt(s_cuad)
s

205544.1783159575

In [323]:
# Calculo de las t's estadisticas para cada coeficiente de regresión
result_t = []
for i in range(0, X.shape[1]):
    t = float(betas[i] / (s * math.sqrt(XT_X_inv[i][i])))
    result_t.append(t)
result_t

[-18.318344955673187,
 14.258429821306533,
 54.09660324932032,
 -5.803793876674154,
 5.980192725915495,
 33.56686574088051,
 24.615553530975262,
 9.77601626190168,
 54.32375149476209,
 -53.5336509660225,
 48.11109078975224,
 34.592710854862595]

# Criterio 1:

In [326]:
# Obtener el valor critico de la t de Student de tablas
import scipy.stats

grados_libertad = len(Y) - X.shape[1]
# La t_critica se obtendrá de un nivel de confianza del 95% (Alfa = 5%)
t_critico = abs(scipy.stats.t.ppf(q = 0.025, df = grados_libertad))
t_critico

1.96007381287675

In [328]:
for i in range(0, X.shape[1]):
    if (abs(result_t[i]) > t_critico):
        print("Beta", i ,"es significativa") # Aquí se rechaza H0
    else:
        print("Beta", i ,"NO es significativa") # Aquí NO se rechaza H0


Beta 0 es significativa
Beta 1 es significativa
Beta 2 es significativa
Beta 3 es significativa
Beta 4 es significativa
Beta 5 es significativa
Beta 6 es significativa
Beta 7 es significativa
Beta 8 es significativa
Beta 9 es significativa
Beta 10 es significativa
Beta 11 es significativa


# Criterio 2:

In [331]:
# Calcxulo de valores p 
for i in range(0, X.shape[1]):
    print("Valor p de Beta", i, ":", scipy.stats.t.sf(abs(result_t[i]), df = grados_libertad) * 2)

Valor p de Beta 0 : 2.1626159087303286e-74
Valor p de Beta 1 : 6.420876607477966e-46
Valor p de Beta 2 : 0.0
Valor p de Beta 3 : 6.573759595988421e-09
Valor p de Beta 4 : 2.2637867159099248e-09
Valor p de Beta 5 : 7.707387984739142e-241
Valor p de Beta 6 : 5.656750886014466e-132
Valor p de Beta 7 : 1.589300562834505e-22
Valor p de Beta 8 : 0.0
Valor p de Beta 9 : 0.0
Valor p de Beta 10 : 0.0
Valor p de Beta 11 : 2.925481366353852e-255


# Criterio 3:

In [334]:
# Calculo de intervalos de confianza del 95% para el verdadero valor del coeficiente de cada Beta
for i in range(0, X.shape[1]):
    print("El valor de Beta", i, "se encuentra entre", float(betas[i]) - t_critico * s * math.sqrt(XT_X_inv[i][i]),
         "y", float(betas[i]) + t_critico * s * math.sqrt(XT_X_inv[i][i]))

El valor de Beta 0 se encuentra entre -39059.902999649414 y -31508.989501220516
El valor de Beta 1 se encuentra entre 39726.202496394406 y 52389.08022490527
El valor de Beta 2 se encuentra entre 161.95938753643262 y 174.13712002807094
El valor de Beta 3 se encuentra entre -0.268521751356268 y -0.13293921078062673
El valor de Beta 4 se encuentra entre 13052.616193911894 y 25780.643272035853
El valor de Beta 5 se encuentra entre 558875.0925681936 y 628191.6139100147
El valor de Beta 6 se encuentra entre 48094.37179152074 y 56416.289479276515
El valor de Beta 7 se encuentra entre 18257.465151100485 y 27414.640901965024
El valor de Beta 8 se encuentra entre 107128.06934097242 y 115148.0913346501
El valor de Beta 9 se encuentra entre -3401.053780689042 y -3160.798995908445
El valor de Beta 10 se encuentra entre 466996.52637522045 y 506664.02330215153
El valor de Beta 11 se encuentra entre 134664.034305386 y 150841.17909688526


In [290]:
# Comparación de resultados contra reporrte automatizado
import statsmodels.api as sm

regressor = sm.OLS(Y, X).fit()
print(regressor.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.901
Model:                            OLS   Adj. R-squared (uncentered):              0.901
Method:                 Least Squares   F-statistic:                          1.638e+04
Date:                Fri, 03 Apr 2026   Prob (F-statistic):                        0.00
Time:                        09:13:56   Log-Likelihood:                     -2.9506e+05
No. Observations:               21613   AIC:                                  5.901e+05
Df Residuals:                   21601   BIC:                                  5.902e+05
Df Model:                          12                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------