In [147]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

import os
os.chdir("/Users/AlanHDLR/Desktop")

In [149]:
data_vw = pd.read_csv("Advertising.csv")
data_vw

,TV,Radio,Newspaper,Sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,12.0
3,151.5,41.3,58.5,16.5
4,180.8,10.8,58.4,17.9
...,...,...,...,...
195,38.2,3.7,13.8,7.6
196,94.2,4.9,8.1,14.0
197,177.0,9.3,6.4,14.8
198,283.6,42.0,66.2,25.5


In [151]:
data_vw["Intercepto"] = 1
X = data_vw[['Intercepto', 'TV', 'Radio', 'Newspaper',]].values
Y = data_vw[["Sales"]].values 

In [153]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=1)

print(f"Registros para entrenamiento: {len(X_train)}")
print(f"Registros para prueba: {len(X_test)}")

Registros para entrenamiento: 140
Registros para prueba: 60


In [155]:
import statsmodels.api as sm
modelo_completo = sm.OLS(y_train, X_train).fit()
print(modelo_completo.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.899
Model:                            OLS   Adj. R-squared:                  0.897
Method:                 Least Squares   F-statistic:                     405.2
Date:                Fri, 03 Apr 2026   Prob (F-statistic):           1.36e-67
Time:                        11:21:35   Log-Likelihood:                -272.35
No. Observations:                 140   AIC:                             552.7
Df Residuals:                     136   BIC:                             564.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.6614      0.368     12.650      0.0

In [157]:
# Nuevo conjunto X solo con variables significativas
X_opt = data_vw[['Intercepto', 'TV', 'Radio']].values 

# Volver a dividir (manteniendo random_state=1)
X_train_opt, X_test_opt, y_train, y_test = train_test_split(X_opt, Y, test_size=0.30, random_state=1)

# Ajustar el nuevo modelo
modelo_final = sm.OLS(y_train, X_train_opt).fit()
print(modelo_final.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.899
Model:                            OLS   Adj. R-squared:                  0.898
Method:                 Least Squares   F-statistic:                     612.0
Date:                Fri, 03 Apr 2026   Prob (F-statistic):           4.95e-69
Time:                        11:21:35   Log-Likelihood:                -272.37
No. Observations:                 140   AIC:                             550.7
Df Residuals:                     137   BIC:                             559.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.6390      0.350     13.240      0.0

In [159]:
XT_X = np.matmul(np.matrix.transpose(X_train_opt), X_train_opt)
XT_X

array([[1.40000000e+02, 1.99806000e+04, 3.24870000e+03],
       [1.99806000e+04, 3.90127308e+06, 4.70424050e+05],
       [3.24870000e+03, 4.70424050e+05, 1.07757590e+05]])

In [161]:
XT_X_inv = np.linalg.inv(XT_X)
XT_X_inv

array([[ 4.19082008e-02, -1.31516536e-04, -6.89312286e-04],
       [-1.31516536e-04,  9.53968372e-07, -1.99632300e-07],
       [-6.89312286e-04, -1.99632300e-07,  3.09331404e-05]])

In [163]:
XT_Y = np.matmul(np.matrix.transpose(X_train_opt), y_train)
XT_Y

array([[  2078.7 ],
       [355094.55],
       [ 51899.21]])

In [165]:
betas = np.matmul(XT_X_inv, XT_Y)
betas

array([[4.63900893],
       [0.05500479],
       [0.10164376]])

In [167]:
# Calculo de Y's pronosticadas
Y_pred = np.matmul(X_train_opt, betas)
Y_pred

array([[13.7491812 ],
       [13.77501043],
       [ 7.97518315],
       [23.60394687],
       [24.14244918],
       [10.08793036],
       [ 9.05039295],
       [16.94043961],
       [18.74206821],
       [ 8.87209621],
       [22.01610705],
       [20.75321283],
       [24.82906764],
       [ 9.03321963],
       [ 9.44539994],
       [18.26187397],
       [ 9.5158188 ],
       [ 8.92268976],
       [22.14970748],
       [15.13523823],
       [17.11359147],
       [12.52420641],
       [18.24589657],
       [17.20402653],
       [ 9.88962303],
       [10.77446835],
       [10.84423778],
       [ 7.86575937],
       [18.06759983],
       [16.55733192],
       [16.31420102],
       [23.77178353],
       [12.99176583],
       [12.52562879],
       [18.09658636],
       [16.72268129],
       [ 7.11627375],
       [15.32014341],
       [10.82543434],
       [14.62348596],
       [10.01042208],
       [18.21552884],
       [ 6.36461151],
       [17.87625466],
       [10.25053979],
       [18

In [169]:
# Calculo de residuales
Resid = y_train - Y_pred
Resid.round(2)

array([[-1.55],
       [-0.38],
       [-2.68],
       [-2.9 ],
       [ 0.26],
       [-2.89],
       [ 2.85],
       [-1.94],
       [ 1.06],
       [ 2.13],
       [-1.82],
       [ 0.95],
       [ 1.37],
       [-1.73],
       [-1.45],
       [ 2.64],
       [-0.32],
       [ 0.48],
       [ 0.05],
       [ 0.36],
       [ 3.49],
       [ 1.48],
       [-0.95],
       [-0.6 ],
       [ 2.01],
       [ 2.93],
       [ 0.46],
       [-2.17],
       [-0.77],
       [-0.46],
       [ 0.89],
       [ 1.63],
       [ 0.31],
       [-2.23],
       [-2.1 ],
       [ 2.98],
       [ 0.48],
       [-0.52],
       [ 0.07],
       [ 2.08],
       [-1.31],
       [-0.72],
       [ 0.94],
       [-1.28],
       [ 1.75],
       [-0.4 ],
       [ 3.06],
       [-5.39],
       [ 0.66],
       [ 1.23],
       [ 0.96],
       [-2.84],
       [ 0.04],
       [ 1.92],
       [ 3.1 ],
       [ 0.66],
       [ 0.81],
       [-7.1 ],
       [ 0.02],
       [ 1.32],
       [-1.88],
       [-0.62],
       [

In [171]:
# Calculo de la suma de residuales al cuadrado
RSS = np.matmul(np.matrix.transpose(Resid), Resid)
RSS

array([[401.35084462]])

In [173]:
# Calculo de la suma total de cuadrados
TSS = np.matmul(np.matrix.transpose(y_train), y_train) - len(y_train)*(y_train.mean()**2)
TSS

array([[3987.34935714]])

In [175]:
# Calculo de coeficiente de determinación 
R_cuad = float(1- RSS/TSS)
R_cuad

0.8993439479032658

In [177]:
# Calculo de la varianza del error de regresión
s_cuad = RSS / (len(y_train) - X_train_opt.shape[1])
s_cuad

array([[2.92956821]])

In [179]:
# Desviación estandar del error de regresión
import math
s = math.sqrt(s_cuad)
s

1.7115981446906272

In [181]:
import scipy.stats

# IMPORTANTE: Usa los datos de entrenamiento (70%) para los grados de libertad
# n = filas de entrenamiento, p = columnas de X (incluyendo intercepto)
n = len(y_train)
p = X_train_opt.shape[1] 
grados_libertad = n - p

# Para un intervalo del 90%, el nivel de confianza es 0.90
Confianza = 0.90 
q = (1 - Confianza) / 2 # Esto dará 0.05 para cada cola

# t_critico para el 90%
t_critico = abs(scipy.stats.t.ppf(q, df = grados_libertad))

print(f"Grados de libertad: {grados_libertad}")
print(f"Valor t crítico (90%): {t_critico:.4f}")

Grados de libertad: 137
Valor t crítico (90%): 1.6561


In [183]:
# Vector de valores particulares de X
# Al eliminar la variable de "newspapper" ya que no era significativa, 
# no ponemos su valor en el ejemplo
f = np.array([[1], [100], [50]])
f

array([[  1],
       [100],
       [ 50]])

In [185]:
Margen_error = t_critico * (s * (float(np.matmul(np.matmul(np.matrix.transpose(f), XT_X_inv), f)) ** 0.5))
Margen_error

0.5034711983440172

In [187]:
Pron_puntual = float(np.matmul(np.matrix.transpose(f), betas))
Pron_puntual

15.221675664877194

In [189]:
# Limites del intervalo de confianza
Lim_inferior = Pron_puntual - Margen_error
Lim_superior = Pron_puntual + Margen_error
print("Intervalo de confienza: (", Lim_inferior, ",", Lim_superior, ")")

Intervalo de confienza: ( 14.718204466533177 , 15.725146863221212 )


# Validación de los supuestos de la regresión 

# Supuesto 1

In [193]:
import scipy
Resid

array([[-1.54918120e+00],
       [-3.75010430e-01],
       [-2.67518315e+00],
       [-2.90394687e+00],
       [ 2.57550822e-01],
       [-2.88793036e+00],
       [ 2.84960705e+00],
       [-1.94043961e+00],
       [ 1.05793179e+00],
       [ 2.12790379e+00],
       [-1.81610705e+00],
       [ 9.46787170e-01],
       [ 1.37093236e+00],
       [-1.73321963e+00],
       [-1.44539994e+00],
       [ 2.63812603e+00],
       [-3.15818800e-01],
       [ 4.77310240e-01],
       [ 5.02925159e-02],
       [ 3.64761768e-01],
       [ 3.48640853e+00],
       [ 1.47579359e+00],
       [-9.45896570e-01],
       [-6.04026526e-01],
       [ 2.01037697e+00],
       [ 2.92553165e+00],
       [ 4.55762223e-01],
       [-2.16575937e+00],
       [-7.67599830e-01],
       [-4.57331917e-01],
       [ 8.85798980e-01],
       [ 1.62821647e+00],
       [ 3.08234174e-01],
       [-2.22562879e+00],
       [-2.09658636e+00],
       [ 2.97731871e+00],
       [ 4.83726255e-01],
       [-5.20143407e-01],
       [ 7.4

In [195]:
# Calculo de la asimetría en los residuales
skew = float(scipy.stats.skew(Resid, bias = True))
skew

-0.5124182186793587

In [197]:
# Calculo de la curtosis de residuales
kurtosis = float(scipy.stats.kurtosis(Resid, fisher = False))
kurtosis

4.782590640126653

In [232]:
Jarque_Bera = (len(y_train)/6) * (skew ** 2 + (kurtosis - 3) ** 2 / 4)
Jarque_Bera

24.662861496030672

In [201]:
Nivel_confianza = 0.90
scipy.stats.chi2.ppf(Nivel_confianza, df = 2)

4.605170185988092

# Supuesto 2: Inexistencia de autocorrelación entre residuales

In [204]:
from statsmodels.formula.api import ols

In [206]:
import pandas as pd
import statsmodels.formula.api as smf
from statsmodels.stats.stattools import durbin_watson

# Definir y_df y x_df con tus datos de entrenamiento
y_df = pd.DataFrame(y_train, columns=['Y'])
x_df = pd.DataFrame(X_train_opt[:, 1:2], columns=['X1'])

# Concatenar para crear el DataFrame del modelo
df = pd.concat([y_df, x_df.reindex(y_df.index)], axis=1)

# Ajustar el modelo usando la fórmula OLS
# Esto calcula: Ventas = Beta0 + Beta1(TV)
model = smf.ols("Y ~ X1", data=df).fit()

# Prueba de Durbin-Watson
dw_result = durbin_watson(model.resid)
print(f"Valor Durbin-Watson: {dw_result}")

Valor Durbin-Watson: 2.032976997799184


# Supuesto 3: Homocedasticidad (Igualdad de varianzas)

In [209]:
ResidCuad = Resid **2
ResidCuad = pd.DataFrame(ResidCuad)
ResidCuad

,0
0,2.399962
1,0.140633
2,7.156605
3,8.432907
4,0.066332
...,...
135,0.285292
136,3.353748
137,0.445398
138,0.245714


In [211]:
X1 = df.iloc[:,1]
X1_df = pd.DataFrame(X1)

X1Cuad = X1 ** 2
X1Cuad_df = pd.DataFrame(X1Cuad)

In [213]:
df_Aux = pd.concat([ResidCuad, X1_df.reindex(y_df.index), X1Cuad_df.reindex(y_df.index)], axis = 1)
df_Aux.columns = ["Residual", "X1", "X1Cuad"]
df_Aux

,Residual,X1,X1Cuad
0,2.399962,139.2,19376.64
1,0.140633,139.3,19404.49
2,7.156605,5.4,29.16
3,8.432907,293.6,86200.96
4,0.066332,281.4,79185.96
...,...,...,...
135,0.285292,219.8,48312.04
136,3.353748,273.7,74911.69
137,0.445398,26.8,718.24
138,0.245714,73.4,5387.56


In [215]:
# Ajuste de regresión lineal multiple
modelAux = ols("Residual ~ X1 + X1Cuad", data = df_Aux).fit()
RSqAux = modelAux.rsquared
RSqAux

0.055255065363579714

In [217]:
Estadistico = len(y_train) * RSqAux
Estadistico

7.73570915090116

In [219]:
Nivel_confianza = 0.95
scipy.stats.chi2.ppf(Nivel_confianza, df = 2)

5.991464547107979

In [221]:
# Alternativa para la prueba de White

from statsmodels.stats.diagnostic import het_white

white_test = het_white(model.resid, model.model.exog)
print("Estadistico de prueba:", white_test[0])
print("Valor p:", white_test[1])

Estadistico de prueba: 13.232837804468922
Valor p: 0.001338214652542002


# Funciones para el calculo de pruebas

In [224]:
# Sesgo y Curtosis
def mis_momentos(residuos):
    n = len(residuos)
    media_res = np.mean(residuos)
    
    # Numeradores (momentos 2, 3 y 4)
    m2 = np.sum((residuos - media_res)**2) / n
    m3 = np.sum((residuos - media_res)**3) / n
    m4 = np.sum((residuos - media_res)**4) / n
    
    sesgo = m3 / (m2**1.5)
    curtosis = m4 / (m2**2)
    
    return sesgo, curtosis

# Comparación
s, c = mis_momentos(modelo_final.resid)
print(f"Mi Sesgo: {s:.3f} | Mi Curtosis: {c:.3f}")

Mi Sesgo: -0.512 | Mi Curtosis: 4.783


In [226]:
# Durbin Watson
def mi_durbin_watson(residuos):
    numerador = np.sum(np.diff(residuos)**2)
    denominador = np.sum(residuos**2)
    return numerador / denominador

print(f"Mi DW: {mi_durbin_watson(modelo_final.resid):.3f}")

Mi DW: 2.038


In [228]:
from scipy import stats
def mi_prueba_white(X, residuos):
    n = len(residuos)
    e2 = residuos**2
    
    #  Crear matriz con términos cuadráticos e interacciones
    # Supongamos X tiene [Const, TV, Radio]
    tv = X[:, 1]
    radio = X[:, 2]
    
    # Matriz de diseño para White: [Const, TV, Radio, TV^2, Radio^2, TV*Radio]
    X_white = np.column_stack([X, tv**2, radio**2, tv*radio])
    
    # Regresión auxiliar
    modelo_aux = sm.OLS(e2, X_white).fit()
    
    # Estadístico LM = n * R^2
    lm_stat = n * modelo_aux.rsquared
    p_val = 1 - stats.chi2.cdf(lm_stat, df=X_white.shape[1] - 1)
    
    return lm_stat, p_val

# Uso (X_train_final incluye la columna de 1s)
lm, p = mi_prueba_white(X_train_opt, modelo_final.resid)
print(f"White LM: {lm:.4f}, p-value: {p:.4f}")

White LM: 11.3534, p-value: 0.0448
